#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Sep 26, 2018 04:43:44 PM IDT  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import test_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = system_control (root)
    test_support.init(root, top)
    root.mainloop()

w = None
def create_system_control(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = system_control (w)
    test_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_system_control():
    global w
    w.destroy()
    w = None


class system_control:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Gentium Basic} -size 10 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("600x450+489+112")
        top.title("system control")
        top.configure(background="#d341d8")



        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.lamp = Button(top)
        self.lamp.place(relx=0.117, rely=0.222, height=76, width=82)
        self.lamp.configure(activebackground="#d9d9d9")
        self.lamp.configure(background="#a477d8")
        self.lamp.configure(borderwidth="0")
        self.lamp.configure(command=test_support.lamp_change(1))
        self.lamp.configure(font=font9)
        self._img1 = PhotoImage(file="./page-icons/page.png")
        self.lamp.configure(image=self._img1)
        self.lamp.configure(relief=GROOVE)
        self.lamp.configure(text='''Bathroom''')
        self.lamp.configure(width=82)

        self.lamp_1 = Button(top)
        self.lamp_1.place(relx=0.267, rely=0.222, height=76, width=82)
        self.lamp_1.configure(activebackground="#d9d9d9")
        self.lamp_1.configure(background="#a477d8")
        self.lamp_1.configure(borderwidth="0")
        self.lamp_1.configure(command=test_support.lamp_change(2))
        self.lamp_1.configure(font=font9)
        self._img2 = PhotoImage(file="./page-icons/page.png")
        self.lamp_1.configure(image=self._img2)
        self.lamp_1.configure(relief=GROOVE)
        self.lamp_1.configure(text='''Bathroom''')

        self.lamp_2 = Button(top)
        self.lamp_2.place(relx=0.267, rely=0.422, height=76, width=82)
        self.lamp_2.configure(activebackground="#d9d9d9")
        self.lamp_2.configure(background="#a477d8")
        self.lamp_2.configure(borderwidth="0")
        self.lamp_2.configure(command=test_support.lamp_change(5))
        self.lamp_2.configure(font=font9)
        self._img3 = PhotoImage(file="./page-icons/page.png")
        self.lamp_2.configure(image=self._img3)
        self.lamp_2.configure(relief=GROOVE)
        self.lamp_2.configure(text='''Bathroom''')

        self.lamp_3 = Button(top)
        self.lamp_3.place(relx=0.417, rely=0.222, height=76, width=82)
        self.lamp_3.configure(activebackground="#d9d9d9")
        self.lamp_3.configure(background="#a477d8")
        self.lamp_3.configure(borderwidth="0")
        self.lamp_3.configure(command=test_support.lamp_change(3))
        self.lamp_3.configure(font=font9)
        self._img4 = PhotoImage(file="./page-icons/page.png")
        self.lamp_3.configure(image=self._img4)
        self.lamp_3.configure(relief=GROOVE)
        self.lamp_3.configure(text='''Bathroom''')

        self.lamp_4 = Button(top)
        self.lamp_4.place(relx=0.133, rely=0.422, height=76, width=82)
        self.lamp_4.configure(activebackground="#d9d9d9")
        self.lamp_4.configure(background="#a477d8")
        self.lamp_4.configure(borderwidth="0")
        self.lamp_4.configure(command=test_support.lamp_change(4))
        self.lamp_4.configure(font=font9)
        self._img5 = PhotoImage(file="./page-icons/page.png")
        self.lamp_4.configure(image=self._img5)
        self.lamp_4.configure(relief=GROOVE)
        self.lamp_4.configure(text='''Bathroom''')






if __name__ == '__main__':
    vp_start_gui()



